version: '3'

services:
  route:
    build:
      context: ./integration-tests/fake_spineroutelookup
      dockerfile: Dockerfile

  fakespine:
    build:
      context: ./
      dockerfile: ./integration-tests/fake_spine/Dockerfile
    ports:
      - "6061:443"
      - "6062:80"
    environment: 
      - FAKE_SPINE_CERTIFICATE
      - FAKE_SPINE_PRIVATE_KEY
      - FAKE_SPINE_CA_STORE
      - INBOUND_SERVER_BASE_URL=https://inbound
      - MHS_LOG_LEVEL=INFO